# Generated by Django 4.1.5 on 2023-01-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_city_customuser_joined_customuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='Сергей', max_length=128),
            preserve_default=False,
        ),
    ]
