# Generated by Django 4.1.5 on 2023-01-16 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_customuser_city_remove_customuser_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Profile',
        ),
    ]
