# Generated by Django 4.1.5 on 2023-02-06 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=128)),
                ('species', models.CharField(choices=[('dogs', 'Собаки'), ('cats', 'Кошки')], max_length=16)),
                ('breed', models.CharField(blank=True, max_length=64, null=True)),
                ('features', models.TextField(blank=True, max_length=2000, null=True)),
                ('hue', models.CharField(blank=True, max_length=32, null=True)),
                ('size', models.CharField(max_length=32)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('boasting', 'Просто хвастаюсь'), ('free_to_take', 'Отдается'), ('on_sale', 'Продается'), ('lost', 'Потеряшка'), ('found', 'Найденыш')], default='boasting', max_length=16)),
                ('avatar', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=50, scale=None, size=[1920, 1080], upload_to='animals')),
                ('avatar_thumbnail', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=50, scale=None, size=[360, 360], upload_to='animals')),
                ('aux_photo', models.ImageField(blank=True, null=True, upload_to='animals')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LostProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=32)),
                ('age', models.CharField(max_length=32)),
                ('loss_city_part', models.CharField(blank=True, max_length=128, null=True)),
                ('loss_street', models.CharField(blank=True, max_length=128, null=True)),
                ('loss_date', models.DateField()),
                ('bounty', models.IntegerField(blank=True, null=True)),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='animals.animal')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring', to='animals.lostprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
