# Generated by Django 4.1.5 on 2023-02-06 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='price',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='status',
        ),
    ]
