# Generated by Django 4.1.5 on 2023-01-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_animal_city_alter_animal_breed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
