# Generated by Django 4.1.5 on 2023-01-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_alter_animal_price'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='animal',
            constraint=models.UniqueConstraint(fields=('owner', 'name', 'species'), name='unique_owner_name_species'),
        ),
    ]
