# Generated by Django 4.1.5 on 2023-02-07 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_remove_lostprofile_age_remove_lostprofile_animal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='lost_profile',
        ),
        migrations.AddField(
            model_name='lostprofile',
            name='animal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lost_profile', to='animals.animal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lostprofile',
            name='loss_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
