# Generated by Django 4.1.5 on 2023-01-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_animal_unique_owner_name_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='found',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='animal',
            name='lost',
            field=models.BooleanField(default=False),
        ),
    ]
