# Generated by Django 4.1.5 on 2023-01-22 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_animal_found_animal_lost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring', to='animals.animal'),
        ),
    ]
