# Generated by Django 4.1.5 on 2023-02-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_alter_lostprofile_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostprofile',
            name='bounty',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
