# Generated by Django 4.1.5 on 2023-02-07 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0006_alter_lostprofile_bounty'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('found_city_part', models.CharField(blank=True, max_length=128, null=True)),
                ('found_street', models.CharField(blank=True, max_length=128, null=True)),
                ('found_date', models.DateField(blank=True, null=True)),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='found_profile', to='animals.animal')),
            ],
        ),
    ]
