# Generated by Django 4.1.5 on 2023-01-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0006_alter_animal_description_alter_animal_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='avatar',
            field=models.ImageField(default='f', upload_to='animals'),
            preserve_default=False,
        ),
    ]
