# Generated by Django 4.1.5 on 2023-01-23 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0007_animal_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='avatar',
        ),
    ]
