# Generated by Django 4.1.5 on 2023-02-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0007_foundprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='accessory',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
