# Generated by Django 4.1.5 on 2023-01-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0008_remove_animal_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalphoto',
            name='is_avatar',
            field=models.BooleanField(default=False),
        ),
    ]
