# Generated by Django 4.1.5 on 2023-02-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0009_rename_accessory_animal_accessories'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostprofile',
            name='nickname',
            field=models.CharField(default='Пряник', max_length=64),
            preserve_default=False,
        ),
    ]
