# Generated by Django 4.1.5 on 2023-01-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0009_animalphoto_is_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='found',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='free_to_take',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='lost',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='on_sale',
        ),
        migrations.AddField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('boasting', 'Просто хвастаюсь'), ('free_to_take', 'Отдается'), ('on_sale', 'Продается'), ('lost', 'Потеряшка'), ('found', 'Найденыш')], default='boasting', max_length=16),
        ),
    ]
