# Generated by Django 4.1.5 on 2023-02-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0010_lostprofile_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='gender',
            field=models.CharField(choices=[('M', 'М'), ('F', 'Ж')], default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PersonalProfile',
        ),
    ]
