# Generated by Django 4.1.5 on 2023-02-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0010_remove_animal_found_remove_animal_free_to_take_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='aux_photo',
            field=models.ImageField(blank=True, null=True, upload_to='animals'),
        ),
        migrations.AddField(
            model_name='animal',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='animals'),
        ),
    ]
