# Generated by Django 4.1.5 on 2023-02-05 14:47

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0013_alter_animal_avatar_alter_animal_avatar_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=75, scale=0.5, size=[1920, 1080], upload_to='animals'),
        ),
    ]
