version: "3.9"

services:

  nginx:
    image: nginx:1.23
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
  
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../static/:/var/html/static/
      - ../media/:/var/html/media/
